version: "3.7"
name: api
services:

  indexer_db:
    image: postgres:14
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: superrecontrasecreto
    ports:
      - 5432:5432
    volumes:
      - /tmp/data_auth:/var/lib/postgresql/data
    networks:
      - backend

  # indexer:
  #   build: ../indexer
  #   environment:
  #     KAFKA_BROKER_URL: broker:9092
  #     DETECTIONS_TOPIC: intellisite.detections
  #     ALERTS_TOPIC: intellisite.alerts
  #     SUSPICIOUS_VEHICLE: SUV

networks:
  backend:
    external: false
  intellisite:
   external: true
