version: "3.7"
name: indexer_mongo
services:

  auth_db:
    image: postgres:14
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: superrecontrasecreto
    ports:
      - 5432:5432
    volumes:
      - /tmp/data_auth:/var/lib/postgresql/data
    networks:
      - backend


  indexer_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: indexer
      MONGO_INITDB_ROOT_PASSWORD: superrecontrasecreto
    ports:
      - 27017:27017
    volumes:
      - /tmp/data_indexer_mongo:/data/db
    networks:
      - backend

  # mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - indexer_db
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: indexer
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: superrecontrasecreto
  #     ME_CONFIG_MONGODB_URL: mongodb://indexer_db:27017
  #     ME_CONFIG_MONGODB_SERVER: indexer_db


  api:
    build: 
      context: ..
      dockerfile: api/Dockerfile-mongo
    depends_on:
      - auth_db
      - indexer_db
    ports:
      - 8000:8000
    environment:
      AUTH_DB_CONNECTION: postgresql://auth:superrecontrasecreto@auth_db:5432/auth
      VEHICLES_DB_CONNECTION: mongodb://indexer:superrecontrasecreto@indexer_db:27017/
      KAFKA_BROKER_URL: broker:9092
      ALERTS_TOPIC: intellisite.alerts
      JWT_KEY: 0ca4e5595f14f2261ef41004fa8b0c4a386a22ea11c1fc9dff20072fb87ea595
      JWT_ALGO: HS256
      JWT_EXPIRE: 30
      JWT_ISSUER: epic
      JWT_AUDIENCE: epic
    networks:
      - backend
      - intellisite
    # command: uvicorn indexer.api.app:app --reload --workers 2 --host 0.0.0.0 --port 8000
    command: python3 -m http.server 1026
    # command: python3 -m indexer.api
    volumes:
      - ../api:/usr/app/api


  indexer:
    build: 
      context: ..
      dockerfile: indexer/Dockerfile-mongo
    depends_on:
      - indexer_db
    environment:
      VEHICLES_DB_CONNECTION: mongodb://indexer:superrecontrasecreto@indexer_db:27017/
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
    command: python3 -m http.server 1026
    networks:
      - backend
      - intellisite
    volumes:
      - ../libs/vehicles_mongo:/usr/app/vehicles_mongo
      - ../indexer:/usr/app/indexer

networks:
  backend:
    external: false
  intellisite:
   external: true
