version: "3.7"
name: indexer_mongo
services:

  auth_db:
    image: postgres:14
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: superrecontrasecreto
    ports:
      - 5432:5432
    volumes:
      - /tmp/data_auth:/var/lib/postgresql/data
    networks:
      - backend

  api_pg:
    image: python:3.9
    # build: 
    #   context: ..
    #   dockerfile: api/Dockerfile
    depends_on:
      - auth_db
    ports:
      - 8000:8000
    environment:
      AUTH_DB_CONNECTION: postgresql://auth:superrecontrasecreto@auth_db:5432/auth
      VEHICLES_DB_CONNECTION: postgresql://indexer:superrecontrasecreto@indexer_db:5432/indexer
      KAFKA_BROKER_URL: broker:9092
      ALERTS_TOPIC: intellisite.alerts
      JWT_KEY: 0ca4e5595f14f2261ef41004fa8b0c4a386a22ea11c1fc9dff20072fb87ea595
      JWT_ALGO: HS256
      JWT_EXPIRE: 30
      JWT_ISSUER: epic
      JWT_AUDIENCE: epic
    networks:
      - backend
      - frontend
    # command: uvicorn indexer.api.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: python3 -m http.server 1026
    volumes:
      - ./scripts:/src/scripts
      - ../libs:/src/libs
      - ../api:/src/api

networks:
  backend:
    external: false
  frontend:
   external: false
